async(page)=>{
 const settle=async root=>{await root.locator('.dz-carousel-viewport').evaluate(v=>new Promise((resolve,reject)=>{if(v.dataset.carouselMoving==='false')return resolve();const timeout=setTimeout(()=>reject(new Error('Carousel did not settle within 7 seconds')),7000);const api=v.dzCarousel;const done=()=>{clearTimeout(timeout);api.off('settle',done);resolve();};api.on('settle',done);}));};
 const firstText=async root=>root.locator('[data-carousel-visible="true"]').evaluateAll(es=>es.sort((a,b)=>a.getBoundingClientRect().left-b.getBoundingClientRect().left)[0]?.textContent);

 await page.bringToFront();const base='http://127.0.0.1:8174',checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const check=(ok,name)=>checks.push({ok,name});
 const slugs=['rasulov-magomed-radzhabovich','murtazalieva-maret-akhmedovna','badunts-karen-valerievich','rasulova-yana-borisovna'];
 for(const width of [1440,768,360,320]){
  await page.setViewportSize({width,height:900});
  for(const slug of slugs){const response=await page.goto(base+'/doctors/'+slug);check(response.status()===200,'Profile '+slug+' '+width);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Profile fits '+slug+' '+width);check(await page.locator('h1').count()===1,'One heading '+slug+' '+width);if(await page.locator('.dz-profile-portrait img').count())check(await page.locator('.dz-profile-portrait img').evaluate(e=>e.complete&&e.naturalWidth>0),'Portrait loaded '+slug+' '+width);}
  await page.goto(base+'/doctors');await page.locator('[data-doctor-search]').fill('Карен');check(await page.locator('[data-doctor-card]:visible').count()===1&&await page.locator('[data-doctor-card]:visible h2').innerText().then(t=>t.includes('Бадунц')),'Directory name filter '+width);await page.locator('[data-doctor-search]').fill('');await page.locator('[data-specialty="6"]').click();check(await page.locator('[data-doctor-card]:visible h2').innerText().then(t=>t.includes('Марет')),'Child specialty '+width);
  await page.goto(base+'/doctors/rasulov-magomed-radzhabovich');const section=page.locator('#certificates');await section.locator('[data-gallery-next]').scrollIntoViewIfNeeded();await page.waitForTimeout(150);const track=section.locator('[data-gallery-track]');const target=await track.locator('[data-certificate-open]').nth(1).getAttribute('href');await section.locator('[data-gallery-next]').click();await settle(section);check(await track.locator('[data-carousel-visible="true"]').evaluateAll(es=>es.sort((a,b)=>a.getBoundingClientRect().left-b.getBoundingClientRect().left)[0].querySelector('[data-certificate-open]').getAttribute('href'))===target,'Certificates move one card '+width);
  const opener=section.locator('[data-certificate-open]').nth(1);await opener.scrollIntoViewIfNeeded();const y=await page.evaluate(()=>scrollY);await opener.click();await page.waitForTimeout(260);const dialog=page.locator('#certificate-viewer');check(await dialog.evaluate(e=>e.open),'Viewer opens '+width);check(await dialog.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.height<=innerHeight;}),'Viewer fits '+width);await page.waitForFunction(()=>{const e=document.querySelector('[data-certificate-full]');return e.complete&&e.naturalWidth>0;});await page.locator('[data-certificate-next]').click();check((await page.locator('[data-certificate-counter]').innerText())==='3 / 16','Viewer next one '+width);await page.locator('[data-certificate-zoom]').click();check(await page.locator('[data-certificate-zoom]').getAttribute('aria-pressed')==='true','Zoom '+width);await page.keyboard.press('Escape');await page.waitForTimeout(260);check(!await dialog.evaluate(e=>e.open),'Viewer closes '+width);check(Math.abs(await page.evaluate(()=>scrollY)-y)<=1,'Viewer no page jump '+width);
  await page.goto(base);const next=page.locator('[data-team-next]').first();await next.scrollIntoViewIfNeeded();await page.waitForTimeout(450);for(let i=0;i<4;i++){const before=await page.evaluate(()=>scrollY);await next.click();await settle(page.locator('[data-team-carousel]').first());check(Math.abs(await page.evaluate(()=>scrollY)-before)<=1,'Team stable '+width+' '+i);}
 }
 await page.goto(base+'/doctors/murtazalieva-maret-akhmedovna');check(await page.locator('[data-certificate-open]').count()===7,'All seven PDF pages');check(await page.locator('#certificates').innerText().then(t=>t.includes('8 июня 2026')),'Accreditation dates retained');
 await page.setViewportSize({width:1440,height:900});await page.goto(base);await page.locator('.dz-search-toggle').click();await page.locator('#site-search-input').fill('Яна');await page.waitForFunction(()=>document.querySelector('#site-search-results a')?.getAttribute('href').includes('rasulova-yana'));check(true,'Global search by name');await page.locator('#site-search-input').fill('имплантолог');await page.waitForFunction(()=>document.querySelector('#site-search-results a')?.getAttribute('href').includes('badunts-karen'));check(true,'Global search by specialty');
 return {checks:checks.length,failures:checks.filter(x=>!x.ok),errors:[...new Set(errors)]};
}
