async (page) => {
  const failures=[];
  const assert=(value,label)=>{if(!value)failures.push(label);};
  const home='http://127.0.0.1:8174/';
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(home);await page.evaluate(()=>localStorage.removeItem('accessibility-settings'));await page.reload();
  await page.setViewportSize({width:1280,height:960});
  await page.evaluate(()=>document.fonts.ready);
  const base=await page.locator('main h1').last().evaluate(e=>parseFloat(getComputedStyle(e).fontSize));
  const serviceTrigger=page.locator('[data-nav-panel="services-menu"]');
  await serviceTrigger.click();await page.waitForFunction(()=>document.querySelector('#services-menu').classList.contains('is-open'));
  assert(await page.locator('#service-links-0').isVisible(),'Initial service category visible');
  await page.locator('[data-service-category="1"]').click();
  assert(await page.locator('#service-links-1 a').count()===6,'Implantation submenu has six source links');
  assert(await page.locator('#service-links-1').isVisible(),'Category click changes submenu');
  const urls=await page.locator('#services-menu [role="tabpanel"] a').evaluateAll(a=>[...new Set(a.map(x=>x.getAttribute('href')))]);
  assert(urls.length===34,'All 34 adult service pages are available');
  await page.locator('[data-service-category="1"]').focus();await page.keyboard.press('ArrowDown');
  assert(await page.locator('[data-service-category="2"]').getAttribute('aria-selected')==='true','Category arrow-key selection');
  await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#services-menu').hidden);
  assert(await serviceTrigger.evaluate(e=>e===document.activeElement),'Escape restores service trigger focus');
  await page.locator('[data-nav-panel="patients-menu"]').click();assert(await page.locator('#patients-menu').isVisible(),'Patient panel opens');
  await page.mouse.click(20,900);await page.waitForFunction(()=>document.querySelector('#patients-menu').hidden);
  await page.locator('.dz-topbar [data-accessibility]').click();
  await page.waitForFunction(()=>document.querySelector('#accessibility-settings').open);
  await page.locator('[data-setting="fontSize"] [data-value="150"]').click();
  const enlarged=await page.locator('main h1').last().evaluate(e=>parseFloat(getComputedStyle(e).fontSize));
  assert(enlarged>=base*1.49,'150% type scale changes actual text');
  await page.locator('[data-setting="colorScheme"] [data-value="white-black"]').click();
  assert(await page.locator('main').evaluate(e=>getComputedStyle(e).backgroundColor)==='rgb(0, 0, 0)','Inverse contrast scheme');
  await page.locator('[data-setting="lineHeight"] [data-value="large"]').click();
  await page.locator('[data-setting="letterSpacing"] [data-value="medium"]').click();
  await page.locator('[data-toggle-images]').click();
  assert(await page.locator('main img').first().evaluate(e=>getComputedStyle(e).opacity)==='0.1','Hide-image setting');
  await page.reload();
  assert(await page.evaluate(()=>document.documentElement.dataset.a11ySize)==='150','Settings survive navigation/reload');
  await page.locator('.dz-topbar [data-accessibility]').click();await page.locator('[data-reset-accessibility]').click();
  assert(await page.evaluate(()=>document.documentElement.dataset.a11ySize)==='100','Reset type settings');
  await page.locator('[data-disable-accessibility]').click();await page.waitForFunction(()=>!document.querySelector('#accessibility-settings').open);
  assert(await page.evaluate(()=>document.documentElement.dataset.a11yEnabled)==='false','Return to normal version');
  for(const width of [360,320]){
    await page.setViewportSize({width,height:900});
    assert(await page.locator('.dz-mobile-actions').isVisible(),'Mobile actions visible at '+width);
    assert(await page.locator('.dz-mobile-actions > *').count()===5,'Five mobile actions at '+width);
    const before=await page.locator('.dz-header').boundingBox();
    await page.evaluate(()=>scrollTo({top:380,behavior:'instant'}));const y=await page.evaluate(()=>scrollY);
    await page.locator('.dz-menu-toggle').click();await page.waitForFunction(()=>document.querySelector('#mobile-menu').classList.contains('is-open'));
    await page.locator('.dz-mobile-services > summary').click();
    await page.locator('.dz-mobile-categories > details').nth(1).locator('summary').click();
    assert(await page.locator('.dz-mobile-categories a[href="/services/ustanovka-implanta"]').isVisible(),'Nested mobile service link at '+width);
    await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#mobile-menu').open);
    const after=await page.locator('.dz-header').boundingBox();
    assert(Math.abs(before.width-after.width)<1,'Stable header at '+width);
    assert(Math.abs(y-await page.evaluate(()=>scrollY))<1,'Stable scroll at '+width);
    assert(await page.locator('.dz-mobile-actions a[href="https://idotvip.ru/domzubov"]').isVisible(),'Bottom action links to the clinic booking service');
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile overflow at '+width);
    const mobileBase=await page.locator('main h1').last().evaluate(e=>parseFloat(getComputedStyle(e).fontSize));
    await page.locator('.dz-mobile-eye').click();await page.locator('[data-setting="fontSize"] [data-value="150"]').click();
    const mobileLarge=await page.locator('main h1').last().evaluate(e=>parseFloat(getComputedStyle(e).fontSize));
    assert(mobileLarge>=mobileBase*1.49,'Exact 150% mobile scaling at '+width);
    assert(await page.locator('#accessibility-settings').evaluate(e=>e.scrollWidth<=e.clientWidth),'Large settings panel reflows at '+width);
    await page.locator('[data-disable-accessibility]').click();await page.waitForFunction(()=>!document.querySelector('#accessibility-settings').open);
    // Reset native disclosures for the next viewport.
    await page.evaluate(()=>document.querySelectorAll('#mobile-menu details').forEach(e=>e.open=false));
  }
  assert(!errors.length,'No browser JS errors: '+errors.join('; '));
  return {failures,servicePages:urls.length,fontScale:{base,enlarged},errors};
}
