async(page)=>{
 const settle=async root=>{await root.locator('.dz-carousel-viewport').evaluate(v=>new Promise((resolve,reject)=>{if(v.dataset.carouselMoving==='false')return resolve();const timeout=setTimeout(()=>reject(new Error('Carousel did not settle within 7 seconds')),7000);const api=v.dzCarousel;const done=()=>{clearTimeout(timeout);api.off('settle',done);resolve();};api.on('settle',done);}));};
 const firstText=async root=>root.locator('[data-carousel-visible="true"]').evaluateAll(es=>es.sort((a,b)=>a.getBoundingClientRect().left-b.getBoundingClientRect().left)[0]?.textContent);

 await page.bringToFront();const base='http://127.0.0.1:8174';const checks=[],errors=[];const check=(ok,name)=>checks.push({name,ok});page.on('pageerror',e=>errors.push(e.message));
 for(const width of [1440,768,360,320]){
  await page.setViewportSize({width,height:1000});await page.goto(base+'/services/lechenie-kariesa');
  check(await page.locator('h1').evaluate(e=>getComputedStyle(e).fontFamily.includes('Russo One')),'Russo One '+width);
  check(await page.locator('[data-feature-card] img').count()===0&&await page.locator('[data-feature-card] svg').count()>=3,'Vector icons '+width);
  const frame=page.locator('[data-case-demo]').first();await frame.scrollIntoViewIfNeeded();await page.waitForTimeout(650);let box=await frame.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height*.5,{steps:12});await page.mouse.up();check(Math.abs(Number(await frame.locator('[type=range]').inputValue())-80)<2,'Compare drag '+width);await frame.locator('[type=range]').focus();await page.keyboard.press('Home');check(await frame.locator('[type=range]').inputValue()==='0','Compare keyboard '+width);
  check(!await page.locator('body').innerText().then(s=>/Визуальная концепция|Иллюстрации атмосферы/.test(s)),'No photo captions '+width);
  await page.goto(base);const team=page.locator('[data-team-carousel]').first();await team.locator('[data-team-next]').scrollIntoViewIfNeeded();await page.waitForTimeout(650);const second=await team.locator('[data-team-card]').nth(1).textContent();let y=await page.evaluate(()=>scrollY);await team.locator('[data-team-next]').click();await settle(team);check(await firstText(team)===second,'Team one card '+width);check(Math.abs(await page.evaluate(()=>scrollY)-y)<=1,'Team no jump '+width);
  const reviews=page.locator('[data-review-carousel]').first();await reviews.locator('[data-review-next]').scrollIntoViewIfNeeded();await page.waitForTimeout(650);const review2=await reviews.locator('[data-review-card]').nth(1).textContent();y=await page.evaluate(()=>scrollY);await reviews.locator('[data-review-next]').click();await settle(reviews);check(await firstText(reviews)===review2,'Review one card '+width);check(Math.abs(await page.evaluate(()=>scrollY)-y)<=1,'Review no jump '+width);check(await reviews.locator('[data-review-card]').count()===31,'All 31 reviews '+width);
  const opener=width>=1280?page.locator('.dz-search-toggle'):width<768?page.locator('.dz-mobile-actions [data-search-open]'):page.locator('.dz-menu-toggle');
  await opener.click();if(width===768)await page.locator('#mobile-menu [data-search-open]').click();await page.waitForTimeout(280);await page.locator('#site-search-input').fill('болит зуб');await page.waitForFunction(()=>document.querySelectorAll('#site-search-results a').length>0);check((await page.locator('#site-search-results a').first().getAttribute('href')).includes('lechenie-kariesa'),'Search symptom '+width);check(await page.locator('#site-search').evaluate(e=>e.scrollWidth<=e.clientWidth),'Search fits '+width);await page.locator('#site-search-input').fill('щщщщщщщщщ');await page.waitForFunction(()=>!document.querySelector('[data-search-empty]').hidden);check(await page.locator('[data-search-empty]').isVisible(),'No results '+width);await page.keyboard.press('Escape');await page.waitForTimeout(260);check(!await page.locator('#site-search-suggestions').isVisible(),'Search Escape '+width);
 }
 await page.goto(base);const phone=page.locator('input[type=tel]').first();await phone.fill('89286996784');check(await phone.inputValue()==='+7 (928) 699-67-84','Full phone paste');await phone.evaluate(e=>e.setSelectionRange(9,9));await phone.press('Backspace');check(await phone.inputValue()==='+7 (926) 996-78-4','Backspace after parenthesis');await phone.press('End');await phone.press('Backspace');check((await phone.inputValue()).replace(/\D/g,'').length===9,'Backspace at end');await phone.fill('8 916 12');check(await phone.inputValue()==='+7 (916) 12','Partial trunk prefix paste');await phone.fill('89286996784');await phone.evaluate(e=>e.setSelectionRange(4,7));await phone.press('Backspace');check((await phone.inputValue()).replace(/\D/g,'').length===8,'Selection delete');for(let i=0;i<15;i++){await phone.press('End');await phone.press('Backspace');}check(await phone.inputValue()==='','Phone fully clears');
 await page.setViewportSize({width:1440,height:1000});await page.goto(base);await page.locator('.dz-search-toggle').click();await page.locator('#site-search-input').fill('брекиты');await page.waitForFunction(()=>document.querySelectorAll('#site-search-results a').length>0);await page.keyboard.press('ArrowDown');check(await page.locator('#site-search-input').getAttribute('aria-activedescendant')!==null,'Search keyboard selection');await page.keyboard.press('Enter');await page.waitForURL('**/services/**');check(page.url().includes('prikusa'),'Typo result navigation');
 await page.goto(base+'/search?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E');check(await page.locator('main').count()===1,'Single main landmark');check(await page.locator('main script').count()===0,'Search escaped input');
 return {checks:checks.length,failures:checks.filter(x=>!x.ok),errors:[...new Set(errors)]};
}
