<dialog id="accessibility-settings" class="dz-dialog dz-accessibility-panel" aria-labelledby="accessibility-title">
<button class="dz-icon-btn dz-dialog-close" type="button" data-close aria-label="Закрыть настройки"><?= icon('close') ?></button>
<p class="dz-eyebrow">Удобно каждому</p><h2 id="accessibility-title">Настройки версии<br>для слабовидящих</h2>
<fieldset><legend>Размер шрифта</legend><div class="dz-setting-options" data-setting="fontSize"><button type="button" data-value="100">Обычный</button><button type="button" data-value="125">Увеличенный</button><button type="button" data-value="150">Крупный</button></div></fieldset>
<fieldset><legend>Цветовая схема</legend><div class="dz-setting-options dz-setting-colors" data-setting="colorScheme"><button type="button" data-value="normal">Обычные цвета</button><button type="button" data-value="black-white"><span aria-hidden="true" class="dz-scheme-sample dz-scheme-white">Аа</span>Чёрным по белому</button><button type="button" data-value="white-black"><span aria-hidden="true" class="dz-scheme-sample dz-scheme-black">Аа</span>Белым по чёрному</button><button type="button" data-value="gold"><span aria-hidden="true" class="dz-scheme-sample dz-scheme-gold">Аа</span>Золотым по чёрному</button></div></fieldset>
<fieldset><legend>Межстрочный интервал</legend><div class="dz-setting-options" data-setting="lineHeight"><button type="button" data-value="normal">Обычный</button><button type="button" data-value="medium">Средний</button><button type="button" data-value="large">Большой</button></div></fieldset>
<fieldset><legend>Межбуквенный интервал</legend><div class="dz-setting-options" data-setting="letterSpacing"><button type="button" data-value="normal">Обычный</button><button type="button" data-value="medium">Средний</button><button type="button" data-value="large">Большой</button></div></fieldset>
<div class="dz-image-setting"><span>Изображения</span><button type="button" data-toggle-images aria-pressed="false"><?= icon('eye') ?><span>Скрыть изображения</span></button></div>
<div class="dz-accessibility-actions"><button type="button" class="dz-settings-reset" data-reset-accessibility>Сбросить настройки</button><button type="button" class="dz-btn" data-disable-accessibility>Обычная версия <?= icon('arrow') ?></button></div>
<p class="dz-sr-only" aria-live="polite" data-accessibility-status></p>
</dialog>
