<?php
require_once __DIR__.'/service-preview.php';
function section_heading(string $eyebrow,string $heading,string $text=''): void { ?><div class="dz-section-head"><div><p class="dz-eyebrow"><?= e($eyebrow) ?></p><h2><?= e($heading) ?></h2></div><?php if($text): ?><p><?= e($text) ?></p><?php endif; ?></div><?php }
function page_intro(string $title,string $lead,string $image='consultation'): void { ?><section class="dz-page-intro dz-shell"><div><nav class="dz-breadcrumb" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><span><?= e($title) ?></span></nav><p class="dz-eyebrow">Дом Зубов · Москва</p><h1><?= e($title) ?></h1><p class="dz-lead"><?= e($lead) ?></p><?= booking_button() ?></div><figure><img src="/assets/images/<?= e($image) ?>.webp" alt="Стоматологический кабинет" width="900" height="600"></figure></section><?php }
function service_cards(bool $all=false): void { $categories=json_decode(file_get_contents(PROJECT_ROOT.'/content/service-menu.json'),true)['categories']; ?><div class="dz-service-grid"><?php foreach($categories as $i=>$category): if(empty($category['items'])||(!$all&&$i>5))continue; ?><article class="dz-service-card"><span class="dz-medical-icon"><?= medical_icon() ?></span><span class="dz-card-index"><?= sprintf('%02d',$i+1) ?></span><h3><?= e($category['name']) ?></h3><div><?php foreach($category['items'] as $item): ?><a href="<?= e($item['link']) ?>"><?= e($item['name']) ?><?= icon('arrow') ?></a><?php endforeach; ?></div></article><?php endforeach; ?></div><?php }
function doctor_cards(): void { ?><div class="dz-team-grid"><?php foreach(['Терапевт','Ортопед','Хирург','Ортодонт'] as $i=>$specialty): ?><article class="dz-team-card" data-doctor-specialty="<?= e($specialty) ?>"><div class="dz-portrait-placeholder"><svg viewBox="0 0 180 200" fill="none" aria-hidden="true"><circle cx="90" cy="65" r="31"/><path d="M26 190v-22c0-37 26-63 64-63s64 26 64 63v22M74 109l16 33 16-33M90 142v48"/></svg><span>Скоро познакомимся</span></div><div><p class="dz-eyebrow">Врач-стоматолог</p><h3><?= e($specialty) ?></h3><p>Имя и фотографию специалиста добавим позже.</p><span class="dz-demo-label">Временная карточка</span></div></article><?php endforeach; ?></div><?php }
function review_carousel(): void { $reviews=[['О первом приёме','Пришла с вопросами по старой пломбе. На консультации мне показали, что нужно проверить, и объяснили возможные варианты. Удобно, когда понятно, с чего начинать.'],['О плане лечения','Мне было важно заранее разобраться в этапах и расходах. В этом примере пациент получает план и может спокойно обсудить его с врачом до начала лечения.'],['О детском приёме','Для первого знакомства с врачом выбрали короткий визит. Ребёнку показали кресло и инструменты, дали время освоиться. Такой подход помог бы нам меньше волноваться.'],['Об удобной записи','В примере пациент выбирает время через онлайн-запись, а детали приёма уточняет по телефону. Всё нужное находится на одной странице.'],['О консультации','Хотелось понять, какие варианты восстановления зуба существуют. В таком отзыве пациент мог бы рассказать, насколько понятно врач объяснил разницу между ними.'],['О внимании к деталям','Для меня важны спокойный разговор и возможность задать вопросы. Здесь будет реальный отзыв пациента о его визите в Дом Зубов.']]; ?><div data-review-carousel class="dz-reviews-widget"><div class="dz-review-grid" aria-live="polite"><?php foreach($reviews as $i=>$review): ?><article class="dz-review-card" data-review-card <?= $i>2?'hidden':'' ?>><span class="dz-quote" aria-hidden="true">“</span><span class="dz-demo-label">Пример отзыва для макета</span><p><?= e($review[1]) ?></p><h3><?= e($review[0]) ?></h3><small>Вымышленный текст · не отзыв пациента</small></article><?php endforeach; ?></div><div class="dz-carousel-controls"><span data-review-status>1–3 из 6</span><button class="dz-icon-btn" type="button" data-review-prev aria-label="Предыдущие отзывы"><?= icon('chevron','dz-prev') ?></button><button class="dz-icon-btn" type="button" data-review-next aria-label="Следующие отзывы"><?= icon('chevron','dz-next') ?></button></div></div><?php }
function locations(bool $maps=true): void { ?><div class="dz-location-grid"><?php foreach(company_locations() as $location): ?><article class="dz-location-card"><p class="dz-eyebrow"><?= e($location['area']) ?></p><h3><?= e($location['name']) ?></h3><p><?= e($location['address']) ?></p><a class="dz-text-link" href="https://yandex.ru/maps/?text=<?= rawurlencode($location['query']) ?>" target="_blank" rel="noopener noreferrer">Построить маршрут <?= icon('arrow') ?></a><?php if($maps): ?><iframe loading="lazy" title="Карта: <?= e($location['address']) ?>" src="https://yandex.ru/map-widget/v1/?text=<?= rawurlencode($location['query']) ?>&amp;z=16" referrerpolicy="no-referrer-when-downgrade"></iframe><?php endif; ?></article><?php endforeach; ?></div><?php }
function price_groups(array $groups): void { foreach($groups as $i=>$group): ?><details class="dz-price-group" <?= $i===0?'open':'' ?>><summary><?= e($group['title']) ?><?= icon('chevron') ?></summary><div><?php foreach($group['items'] as $item): ?><div class="dz-price-row"><span><?= e($item['name']) ?></span><strong><?= e($item['price']) ?></strong></div><?php endforeach; ?></div></details><?php endforeach; }
function cta_section(): void { ?><section class="dz-booking-section dz-dark"><div class="dz-shell"><p class="dz-eyebrow">Начнём с разговора</p><h2>Найдём решение<br>для вашей улыбки</h2><p>Выберите удобное время приёма. Врач проведёт осмотр, ответит на вопросы и обсудит с вами дальнейшие шаги.</p><?= booking_button('Записаться онлайн') ?><a class="dz-cta-phone" href="tel:<?= COMPANY_TEL ?>"><?= COMPANY_PHONE ?></a></div></section><?php }
?>
<?php if($route==='index'): ?>
<section class="dz-new-hero dz-dark"><img class="dz-hero-photo" src="/assets/images/reception.webp" alt="Ресепшен стоматологии" width="1536" height="1024" fetchpriority="high"><div class="dz-shell dz-hero-copy"><p class="dz-eyebrow">Стоматология, где вам рады</p><h1>Здоровая улыбка —<br><span>часть вашей<br>истории</span></h1><p class="dz-lead">От первого вопроса до завершения лечения.<br>Внимательно, понятно и с заботой о вас.</p><div class="dz-hero-actions"><?= booking_button() ?><a class="dz-btn dz-btn-outline" href="/prices">Стоимость услуг</a></div><div class="dz-hero-points"><span><?= medical_icon() ?>Все направления<br>стоматологии</span><span><?= icon('shield') ?>Понятный<br>план лечения</span><span><?= icon('pin') ?>Симферопольский<br>бульвар, 24, к. 4</span></div></div></section>
<section class="dz-section dz-shell"><?php section_heading('Услуги','Всё, что нужно для здоровья ваших зубов','Лечение, восстановление и эстетика. Выберите направление, чтобы узнать, как проходит приём.'); service_preview(); ?><a class="dz-text-link dz-section-link" href="/services">Все услуги <?= icon('arrow') ?></a></section>
<section class="dz-about-band dz-dark"><div class="dz-shell dz-split"><figure><img src="/assets/images/treatment-room.webp" alt="Стоматологический кабинет" width="900" height="600" loading="lazy"></figure><div><p class="dz-eyebrow">О клинике</p><h2>Дом Зубов.<br>Место, где вас<br>слышат</h2><p>Зуб может болеть, улыбка — вызывать вопросы, а предстоящий приём — тревогу. Начнём с того, что выслушаем вас.</p><p>Обсудим состояние зубов, объясним варианты лечения и составим последовательный план. Вы сможете задать вопросы и принять решение без спешки.</p><a href="/o-nas" class="dz-btn">Подробнее о клинике <?= icon('arrow') ?></a></div></div></section>
<section class="dz-section dz-shell"><?php section_heading('Команда','Знакомство с врачами','Готовим раздел с фотографиями и информацией о наших специалистах.'); doctor_cards(); ?></section>
<section class="dz-values dz-dark"><div class="dz-shell"><h2>Что важно<br>для нас</h2><?php foreach([['shield','Бережное отношение'],['document','Понятные объяснения'],['wallet','Обсуждение стоимости'],['pin','Удобная запись']] as [$symbol,$text]): ?><div><?= icon($symbol) ?><span><?= e($text) ?></span></div><?php endforeach; ?></div></section>
<section class="dz-section dz-shell"><?php section_heading('Обратная связь','Здесь будут ваши истории','Пока показаны примеры оформления. Настоящие отзывы добавим после получения согласия пациентов.'); review_carousel(); ?></section>
<section class="dz-section dz-dark"><div class="dz-shell dz-faq-layout"><div><p class="dz-eyebrow">Вопросы и ответы</p><h2>Перед первым<br>приёмом</h2></div><div><?php foreach([['Как записаться?','Нажмите «Записаться на приём»: откроется страница онлайн-записи. Также можно позвонить нам по телефону '.COMPANY_PHONE.'.'],['Что взять с собой?','Возьмите документ, удостоверяющий личность. Если у вас есть снимки, заключения или предыдущий план лечения, покажите их врачу.'],['Когда станет известна стоимость?','Предварительные цены доступны в разделе «Стоимость лечения». Объём и итоговую стоимость врач уточнит после осмотра и диагностики.'],['Можно ли прийти только на консультацию?','Да. На консультации можно обсудить жалобы, задать вопросы и узнать о возможных вариантах лечения.']] as [$question,$answer]): ?><details class="dz-faq"><summary><?= e($question) ?><?= icon('chevron') ?></summary><p><?= e($answer) ?></p></details><?php endforeach; ?></div></div></section>
<section class="dz-section dz-shell"><?php section_heading('Контакты','Мы рядом. И всегда на связи','Два адреса в Москве. Запишитесь онлайн или позвоните — поможем выбрать удобное время.');locations(); ?></section>
<?php elseif($service): ?>
<?php page_intro($service['title'],$service['lead']); ?>
<section class="dz-section dz-shell dz-reading"><p class="dz-eyebrow">О лечении</p><h2><?= e($service['introTitle']) ?></h2><?php foreach($service['intro'] as $paragraph): ?><p><?= e($paragraph) ?></p><?php endforeach; ?></section>
<section class="dz-section dz-muted"><div class="dz-shell"><?php section_heading('Когда обратиться','В каких случаях это нужно'); ?><div class="dz-indication-grid"><?php foreach($service['indications'] as $item): ?><article><span class="dz-medical-icon"><?= medical_icon() ?></span><div><h3><?= e($item['title']) ?></h3><p><?= e($item['text']) ?></p></div></article><?php endforeach; ?></div></div></section>
<section class="dz-section dz-treatment-steps dz-dark"><div class="dz-shell"><?php section_heading('Шаг за шагом','Как проходит лечение'); ?><div class="dz-step-grid"><?php foreach($service['steps'] as $i=>$step): ?><article><span class="dz-step-number"><?= sprintf('%02d',$i+1) ?></span><h3><?= e($step['title']) ?></h3><p><?= e($step['text']) ?></p></article><?php endforeach; ?></div><div class="dz-section-link"><?= booking_button('Записаться на консультацию') ?></div></div></section>
<section class="dz-section dz-shell dz-split"><figure><img src="/assets/images/treatment-room.webp" alt="Стоматологический кабинет" width="900" height="600" loading="lazy"></figure><div><p class="dz-eyebrow">Перед визитом</p><h2>Как подготовиться</h2><ul class="dz-check-list"><?php foreach($service['preparation'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul></div></section>
<?php $priceData=json_decode(file_get_contents(PROJECT_ROOT.'/content/price-catalog.json'),true)['services']['/'.$route]??[]; if($priceData): ?><section class="dz-section dz-muted"><div class="dz-shell"><?php section_heading('Цены','Стоимость лечения','Окончательная стоимость зависит от объёма лечения и уточняется на консультации.');price_groups($priceData); ?></div></section><?php endif; ?>
<?php $cases=json_decode(file_get_contents(PROJECT_ROOT.'/content/case-examples.json'),true)['/'.$route]??[];if($cases): ?><section class="dz-section dz-shell"><?php section_heading('Разбор ситуаций','Примеры клинических случаев','Демонстрационные материалы для структуры сайта. Это не результаты лечения пациентов «Дома Зубов».'); ?><div class="dz-case-grid"><?php foreach($cases as $i=>$case): ?><article class="dz-case-card"><span class="dz-demo-label">Демонстрационный кейс <?= $i+1 ?></span><h3>Ситуация</h3><p><?= e($case['history']) ?></p><details class="dz-faq"><summary>План и ход лечения <?= icon('chevron') ?></summary><p><?= e(str_replace(['Мы провели','мы получили','мы использовали'],['Были проведены','были получены','были использованы'],$case['treatment'])) ?></p></details><div class="dz-case-placeholder">Фотографии до и после добавим после согласования материалов</div></article><?php endforeach; ?></div></section><?php endif; ?>
<section class="dz-section dz-dark"><div class="dz-shell dz-faq-layout"><div><p class="dz-eyebrow">Полезно знать</p><h2>Частые вопросы</h2></div><div><?php foreach($service['faq'] as $item): ?><details class="dz-faq"><summary><?= e($item['question']) ?><?= icon('chevron') ?></summary><p><?= e($item['answer']) ?></p></details><?php endforeach; ?></div></div></section>
<section class="dz-section dz-shell"><?php section_heading('Другие направления','Также может быть полезно'); ?><div class="dz-related"><?php foreach($service['related'] as $link): $key=ltrim($link,'/');$related=editorial_services()[$key]??null;if(!$related)continue; ?><a href="/<?= e($key) ?>"><?= medical_icon() ?><span><?= e($related['title']) ?></span><?= icon('arrow') ?></a><?php endforeach; ?></div></section><?php cta_section(); ?>
<?php elseif($route==='services'): page_intro('Все услуги','От профилактики до сложного восстановления. Выберите направление — на странице услуги рассказываем о показаниях, этапах и подготовке.'); ?><section class="dz-section dz-shell"><?php service_cards(true); ?></section><?php cta_section(); ?>
<?php elseif(in_array($route,['contacts','taganka','chertanovskaya'],true)): ?>
<section class="dz-section dz-shell"><p class="dz-eyebrow">Дом Зубов · Москва</p><h1><?= e($title) ?></h1><div class="dz-contact-top"><a href="tel:<?= COMPANY_TEL ?>"><?= COMPANY_PHONE ?></a><a href="mailto:<?= COMPANY_EMAIL ?>"><?= COMPANY_EMAIL ?></a><?= booking_button() ?></div><?php locations(); ?><p class="dz-note">Время приёма уточняйте при записи.</p></section>
<?php elseif($route==='doctors'): ?>
<section class="dz-section dz-shell"><p class="dz-eyebrow">Команда Дома Зубов</p><h1>Врачи</h1><p class="dz-lead">Здесь появятся фотографии, имена и профессиональная информация наших специалистов. Пока оставили временные карточки по направлениям.</p><div class="dz-select dz-doctor-filter"><button type="button" data-select-trigger aria-haspopup="listbox" aria-expanded="false" aria-controls="specialties"><span data-select-label>Все специалисты</span><?= icon('chevron') ?></button><div class="dz-select-options" id="specialties" role="listbox" aria-label="Специализация врача" hidden><?php foreach(['Все специалисты','Терапевт','Ортопед','Хирург','Ортодонт'] as $i=>$specialty): ?><button type="button" role="option" aria-selected="<?= $i===0?'true':'false' ?>" data-value="<?= $i===0?'all':e($specialty) ?>"><?= e($specialty) ?></button><?php endforeach; ?></div></div><?php doctor_cards(); ?></section><?php cta_section(); ?>
<?php elseif($route==='reviews'): ?>
<section class="dz-section dz-shell"><p class="dz-eyebrow">Обратная связь</p><h1>Отзывы пациентов</h1><p class="dz-lead">Раздел готовится к публикации. Ниже — вымышленные примеры для макета, а не отзывы о работе клиники.</p><?php review_carousel(); ?></section><?php cta_section(); ?>
<?php elseif($route==='prices'): page_intro('Стоимость лечения','Ознакомьтесь с ценами по направлениям. После диагностики врач обсудит с вами необходимый объём лечения и составит план.'); ?><section class="dz-section dz-shell"><?php price_groups(json_decode(file_get_contents(PROJECT_ROOT.'/content/price-catalog.json'),true)['groups']); ?><p class="dz-note">Указаны предварительные цены. Состав и стоимость лечения уточняются на приёме.</p></section><?php cta_section(); ?>
<?php elseif(str_starts_with($route??'','yuridicheskaya-informatsiya')): require __DIR__.'/legal.php'; ?>
<?php elseif($route==='privacy-policy'): ?>
<section class="dz-section dz-shell dz-reading"><p class="dz-eyebrow">Документы</p><h1>Конфиденциальность</h1><p>Владелец сайта — ООО «ДОМ ЗУБОВ», ИНН 9727136018. Связаться с нами можно по адресу <a href="mailto:<?= COMPANY_EMAIL ?>"><?= COMPANY_EMAIL ?></a>.</p><h2>Как устроен сайт</h2><p>Формы обращения на сайте подготавливают письмо в вашей почтовой программе. Отправка происходит, только когда вы отправляете это письмо самостоятельно. Для записи вы переходите на отдельный сервис idotvip.ru, где действуют его условия обработки данных. При обращении по телефону или электронной почте сообщайте только сведения, необходимые для ответа на ваш запрос.</p><h2>Настройки и внешние сервисы</h2><p>Запросы поиска обрабатываются сервером сайта для показа подсказок. Последние выбранные запросы сохраняются в sessionStorage только в текущей вкладке; их можно удалить в выпадающей панели поиска. Выбранные настройки версии для слабовидящих сохраняются в браузере. Их можно сбросить в панели настроек. Встроенные карты загружаются с Яндекса; при их использовании применяются правила этого сервиса.</p><p>Полный комплект документов по обработке персональных данных будет размещён после утверждения владельцем сайта.</p><a class="dz-text-link" href="/yuridicheskaya-informatsiya">Реквизиты организации <?= icon('arrow') ?></a></section>
<?php elseif($editorial): page_intro($editorial['title'],$editorial['lead'],$route==='o-nas'?'reception':'consultation'); ?><section class="dz-section dz-shell dz-reading"><?php foreach($editorial['sections'] as $section): ?><h2><?= e($section['title']) ?></h2><?php foreach($section['paragraphs'] as $paragraph): ?><p><?= e($paragraph) ?></p><?php endforeach; ?><?php endforeach; ?></section><?php cta_section(); ?>
<?php elseif($route==='sitemap'): require __DIR__.'/sitemap.php'; ?>
<?php elseif($route!==null): ?><section class="dz-section dz-shell dz-reading"><p class="dz-eyebrow">Дом Зубов</p><h1>Информация обновляется</h1><p>Мы готовим актуальные условия и материалы для этого раздела. За подробностями обратитесь к администратору.</p><a class="dz-text-link" href="tel:<?= COMPANY_TEL ?>"><?= COMPANY_PHONE ?></a><div class="dz-section-link"><?= booking_button() ?></div></section>
<?php else: ?><section class="dz-section dz-shell"><p class="dz-eyebrow">404</p><h1>Страница не найдена</h1><p>Выберите нужное направление в меню услуг или вернитесь на главную.</p><a class="dz-btn" href="/">На главную <?= icon('arrow') ?></a></section><?php endif; ?>
