<?php require_once __DIR__.'/doctor-card.php'; ?>
<section class="dz-profile-hero dz-shell">
 <nav class="dz-breadcrumb" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/doctors">Врачи</a><span>/</span><span><?= e($doctor['name']) ?></span></nav>
 <div class="dz-profile-hero-grid"><div class="dz-profile-portrait"><?= doctor_portrait($doctor,'',true) ?></div><div class="dz-profile-intro"><p class="dz-eyebrow">Команда «Дома Зубов»</p><h1><?= e($doctor['name']) ?></h1><p class="dz-profile-profession"><?= e($doctor['profession']) ?></p><p class="dz-profile-lead"><?= e($doctor['intro']) ?></p><div class="dz-profile-facts"><?php if($doctor['practiceSince']): ?><div><?= icon('document') ?><span>Практикует с <?= (int)$doctor['practiceSince'] ?> года</span></div><?php endif; ?><div><?= icon('calendar') ?><span><?= e($doctor['schedule']) ?></span></div><div><?= icon('pin') ?><span><?= e(company_locations()[0]['address']) ?></span></div></div><div class="dz-profile-cta"><?= booking_button() ?><a href="tel:<?= COMPANY_TEL ?>"><?= COMPANY_PHONE ?></a></div></div></div>
</section>
<nav class="dz-profile-sections dz-shell" aria-label="Разделы профиля"><a href="#approach">Подход к лечению</a><a href="#education">Образование</a><a href="#expertise">Направления работы</a><?php if($doctor['certificates']): ?><a href="#certificates">Документы и сертификаты <span><?= count($doctor['certificates']) ?></span></a><?php endif; ?></nav>
<section class="dz-profile-section dz-shell dz-profile-about" id="approach"><div><p class="dz-eyebrow">Внимание к пациенту</p><h2>Подход к лечению</h2></div><div><?php foreach($doctor['approach'] as $paragraph): ?><p><?= e($paragraph) ?></p><?php endforeach; ?></div></section>
<section class="dz-profile-section dz-profile-education" id="education"><div class="dz-shell"><p class="dz-eyebrow">Профессиональная подготовка</p><h2>Образование</h2><ol class="dz-education-list"><?php foreach($doctor['education'] as $education): ?><li><span><?= $education['year']!==''?e($education['year']):icon('document') ?></span><p><?= e($education['title']) ?></p></li><?php endforeach; ?></ol></div></section>
<section class="dz-profile-section dz-shell" id="expertise"><p class="dz-eyebrow">Чем занимается врач</p><h2>Направления работы</h2><div class="dz-competency-grid"><?php foreach($doctor['competencies'] as $i=>$item): ?><article><span><?= sprintf('%02d',$i+1) ?></span><h3><?= e($item['title']) ?></h3><p><?= e($item['text']) ?></p></article><?php endforeach; ?></div><div class="dz-doctor-services"><?php foreach($doctor['services'] as $url): $serviceInfo=editorial_services()[ltrim($url,'/')]??null;if(!$serviceInfo)continue; ?><a href="<?= e($url) ?>"><?= e($serviceInfo['title']) ?><?= icon('arrow') ?></a><?php endforeach; ?></div></section>
<?php if($doctor['certificates']): ?><section class="dz-profile-section dz-certificates" id="certificates" data-gallery><div class="dz-shell"><div class="dz-certificate-heading"><div><p class="dz-eyebrow">Образование и обучение</p><h2>Документы и сертификаты</h2></div><div class="dz-certificate-controls"><button type="button" class="dz-icon-btn" data-gallery-prev aria-label="Предыдущий сертификат"><?= icon('arrow') ?></button><button type="button" class="dz-icon-btn" data-gallery-next aria-label="Следующий сертификат"><?= icon('arrow') ?></button></div></div><p class="dz-certificate-intro">Нажмите на документ, чтобы рассмотреть его крупнее.</p><div class="dz-certificate-track" data-gallery-track>
<?php foreach($doctor['certificates'] as $i=>$certificate): ?><article class="dz-certificate-card"><a class="dz-certificate-image" href="<?= e($certificate['image']) ?>" data-certificate-open data-certificate-index="<?= $i ?>" data-certificate-title="<?= e($certificate['title']) ?>" data-certificate-original="<?= e($certificate['document']??$certificate['image']) ?>" aria-label="Открыть: <?= e($certificate['title']) ?>"><img src="<?= e($certificate['thumbnail']) ?>" alt="<?= e($certificate['title']) ?>" width="500" height="360" loading="lazy" decoding="async"><span><?= icon('search') ?></span></a><div class="dz-certificate-card-copy"><p><?= e($certificate['category']) ?><?= $certificate['year']?' · '.(int)$certificate['year']:'' ?></p><h3><?= e($certificate['title']) ?></h3><?php if(!empty($certificate['note'])): ?><small><?= e($certificate['note']) ?></small><?php endif; ?></div></article><?php endforeach; ?>
</div></div></section>
<dialog class="dz-dialog dz-certificate-dialog" id="certificate-viewer" aria-labelledby="certificate-title"><div class="dz-certificate-toolbar"><p id="certificate-title"></p><button class="dz-icon-btn" type="button" data-close aria-label="Закрыть документ"><?= icon('close') ?></button></div><div class="dz-certificate-canvas"><img data-certificate-full alt=""></div><div class="dz-certificate-toolbar"><div class="dz-certificate-controls"><button type="button" class="dz-icon-btn" data-certificate-prev aria-label="Предыдущий документ"><?= icon('arrow') ?></button><span data-certificate-counter aria-live="polite"></span><button type="button" class="dz-icon-btn" data-certificate-next aria-label="Следующий документ"><?= icon('arrow') ?></button></div><button type="button" class="dz-certificate-zoom" data-certificate-zoom aria-pressed="false">Увеличить</button><a data-certificate-download target="_blank" rel="noopener noreferrer">Открыть оригинал <?= icon('arrow') ?></a></div></dialog>
<?php endif; ?>
<section class="dz-profile-booking dz-shell"><div><p class="dz-eyebrow">Дом Зубов</p><h2>Запись на консультацию</h2><p><?= e($doctor['schedule']) ?>.<br><?= e(company_locations()[0]['address']) ?></p></div><?= booking_button() ?></section>
